[build]
  publish = "dist"
  functions = "dist/netlify/functions"
  command = "npm run deploy"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/externalapi/*"
  status = 200
  to = "/.netlify/functions/externalapi/:splat"
  