[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/externalapi/*"
  status = 200
  to = "/.netlify/functions/externalapi/:splat"
[build]
  # Custom build command
  command = "npm test && npm run build" # First run tests, then build
